### ISSUE TITLE
worflow chart

### ISSUE THREAD

**Issue by Thexiyang** [mgabriell1/EUKsemble#1]
Hi. Thanks for the nice tool! Is there any work flow chart for this pipeline?

**Comment by mgabriell1** [comment]
Hi,
Thanks for your interest in EUKsemble!
Yes, that is a good suggestion. 
I'll upload one soon and I'll update you here.

Marco

**Comment by mgabriell1** [comment]
Hi!
Sorry for taking a while, but I finally uploaded the workflow chart of the pipeline.
Let me know if it's clear enough.

Marco

**Comment by Thexiyang** [comment]
A small question here. Why not also include Eukrep here?

**Comment by mgabriell1** [comment]
I chose not to include it as in my benchmarks, it always gave very liberal results which affected too negatively the precision of the k-mer-based majority voting strategy (even tough increasing somewhat the recall).
I am working on finalizing a manuscript including all these benchmarking details and I will post it (or the preprint) as soon as it is ready
