### ISSUE TITLE
space found in pattern, you may need use -n/--by-name

### ISSUE THREAD

**Issue by LuisGuz** [mgabriell1/EUKsemble#2]
Dear Marco.
Hope you are doing well.
I'm interested in testing your pipeline with my dataset.
After running the pipeline I'm getting the following output at "Perform majority classification":

── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (5): X1, X2, X6, X7, X8
dbl (2): X3, X4
num (1): X5

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Warning message:
One or more parsing issues, call `problems()` on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat) 
===============================================
Extract eukaryotic contigs in new fasta file 
[WARN] space found in pattern, you may need use -n/--by-name: "k141_1086627 flag=1 multi=6.0000 len=3222"
[WARN] space found in pattern, you may need use -n/--by-name: "k141_352465 flag=1 multi=7.0000 len=3348"
[WARN] space found in pattern, you may need use -n/--by-name: "k141_1439061 flag=1 multi=9.0000 len=3518"
[WARN] space found in pattern, you may need use -n/--by-name: "k141_1644666 flag=0 multi=15.9121 len=3268"
[WARN] space found in pattern, you may need use -n/--by-name: "k141_939854 flag=0 multi=16.6889 len=8562"
[WARN] space found in pattern, you may need use -n/--by-name: "k141_1644675 flag=1 multi=6.0000 len=3455"
.
etc
.
.
[INFO] 2274 patterns loaded from file
$
After this, I'm getting 2 output files, 'kaiju.out' and 'kaiju.taxa.out'

Should I modify the Majority_classification_extInput.R ? or maybe some input file format?
I'd appreciate some help.
Best regards.

**Comment by mgabriell1** [comment]
Dear Luis,
Thanks for your interested in the pipeline! 
No you shouldn't be changing that script. As you said it's either an issue with the input files or something that I need to change in the script myself.

One thing that might be causing problems is the fact that there are several whitespaces in your contigs names. You can substitute it with an underscore using sed like `sed 's/old-text/new-text/g' orig_contigs.fasta > renamed_contigs.fasta`.
The warning message `[WARN] space found in pattern, you may need use -n/--by-name: ...` comes from seqkit which by defaults expects no whitespaces in the contigs names. Also I think Whokaryote (don't remember precisely though) might have some problems with the output in case a whitespace is present.

Also, have you run Kaiju locally? In that case, `kaiju.taxa.out` should be created at the "KAIJU CLASSIFICATION" step not while performing tha majority classification. Could you share with the the full log?

**Comment by LuisGuz** [comment]
Thank you for your prompt reply Marco, and sorry I could't test this earlier.
I think it worked now and I got the contigs file "renamed_contigs.EUK_NA_KmerMajority_min3000bp_KAIJU_min1000bp.fa"
I'll test binning with concoct and metabat2.
Also here is the log:

[log1.txt](https://github.com/mgabriell1/EUKsemble/files/11023526/log1.txt)

Best wishes.

**Comment by mgabriell1** [comment]
Sorry for the late reply, but, yes, looking at the log everything looks fine.
Best
