### ISSUE TITLE
Compatibility issue: DeepMicrobeFinder is now DeepMicroClass

### ISSUE THREAD

**Issue by JarrigeD** [mgabriell1/EUKsemble#3]
Dear Marco,

Thank you for making `EUKsemble` available! I'm very interested in this workflow and would like to integrate it as a step in my soil metagenomics data processing.

However, I have encountered several difficulties while trying to run it.

`DeepMicrobeFinder` is now distributed as `DeepMicroClass`, with a different way to run the tool on the command line. And so, I struggled to make `EUKsemble` work. I believe modifying this part of `EUKsemble.sh` might do the trick:

```
if [ ! -f $FOLDER"/"$RESULTS_FOLDER"/deepmicrobefinder-results_min"$MINSIZE_CONTIGS_KMERCLASS"bp/"$DATA"_min"$MINSIZE_CONTIGS_KMERCLASS"bp"$FILE_EXT"_pred_one-hot_hybrid.class.txt" ]; then
    python $DEEPMICROBEFINDER_FOLDER"/predict.py" \
        -i $FOLDER"/"$RESULTS_FOLDER"/"$DATA"_min"$MINSIZE_CONTIGS_KMERCLASS"bp"$FILE_EXT  \
        -e one-hot \
        -d $DEEPMICROBEFINDER_FOLDER"/models/one-hot-models/" \
        -m hybrid \
        -o $FOLDER"/"$RESULTS_FOLDER"/deepmicrobefinder-results_min"$MINSIZE_CONTIGS_KMERCLASS"bp"
```
My suggested modification that seems to make the `DeepMicroClass` run:

```
if [ ! -f $FOLDER"/"$RESULTS_FOLDER"/deepmicrobefinder-results_min"$MINSIZE_CONTIGS_KMERCLASS"bp/"$DATA"_min"$MINSIZE_CONTIGS_KMERCLASS"bp"$FILE_EXT"_pred_one-hot_hybrid.class.txt" ]; then
    DeepMicroClass predict \
        -i $FOLDER"/"$RESULTS_FOLDER"/"$DATA"_min"$MINSIZE_CONTIGS_KMERCLASS"bp"$FILE_EXT \
        -o $FOLDER"/"$RESULTS_FOLDER"/deepmicrobefinder-results_min"$MINSIZE_CONTIGS_KMERCLASS"bp" \
        --encoding onehot \
        --mode hybrid
        #--model $DEEPMICROBEFINDER_FOLDER"/models/one-hot-models/" \
```
I  had problems with the `model` part, as the architecture of the tool seems to have changed and I could not figure what to put as a parameter, so I just commented it out. 
Also the output of `DeepMicroClass` now uses `onehot_hybrid.tsv` instead of `one-hot_hybrid.txt` in the file names, so to be able to run `EUKsemble`, I also changed theses instances in `EUKsemble.sh`.

Do you think these could be reasonable fixes? 

Best regards,
Domitille

**Comment by mgabriell1** [comment]
Dear Domitille,
Thanks for your interest in `EUKsemble` and for already finding a solution to the issue!
I will implement these chances as soon as possible and try in the meanwhile to check for new inconsistencies regarding new dependencies versions. This also reminds me that I should specify their versions in the `README` file.
I'll get back to you soon.
Cheers,

Marco

**Comment by mgabriell1** [comment]
Now it should work with the new dependencies.
Cheers,

Marco
