### ISSUE TITLE
INCLUDE_NA="TRUE" does not output the MajorityKmer_Kaiju_class == NA contigs

### ISSUE THREAD

**Issue by JarrigeD** [mgabriell1/EUKsemble#4]
Dear Marco,

I noted a problem with the `INCLUDE_NA="TRUE"` option, it does not output the NA `MajorityKmer_Kaiju_class` == NA contigs as expected in the results files.

In my `EUKsemble-CONFIG.conf`` file:
```
### Include NAs in output fasta ###
INCLUDE_NA="TRUE" # TRUE/FALSE
```
My results:
```
grep -v "OTHER$" results/MEGAHIT_assembly/EUKsemble_classification/megahit_sols.contigs.1000.Classification_details_KmerMajority_min3000bp_KAIJU_min1000bp.tsv
ContigID        Kaiju_class     Whokaryote_class        Tiara_class     DeepMicrobeFinder_class MajorityKmer_Nclassifications   MajorityKmer_votesFrac  MajorityKmer_class      MajorityKmer_Kaiju_class
k141_1419_flag=1_multi=3.0000_len=1442  NA      NA      NA      NA      0       NA      NA      NA
k141_475_flag=1_multi=3.0000_len=1306   NA      NA      NA      NA      0       NA      NA      NA
k141_1298_flag=1_multi=1.0000_len=1103  EUK     NA      NA      NA      0       NA      NA      EUK
k141_5958_flag=0_multi=1.6596_len=1219  EUK     NA      NA      NA      0       NA      NA      EUK
k141_7362_flag=1_multi=2.6556_len=1224  NA      NA      NA      NA      0       NA      NA      NA

cat results/MEGAHIT_assembly/EUKsemble_classification/megahit_sols.contigs.1000.EUK_NA_contigsIDs_KmerMajority_min3000bp_KAIJU_min1000bp.txt
k141_1298_flag=1_multi=1.0000_len=1103
k141_5958_flag=0_multi=1.6596_len=1219
```

As you can see here, the three NA contigs are left out from the output.

I believe this is because filter() in `Majority_classification_extInput.R` drops NA values [(documentation)](https://dplyr.tidyverse.org/reference/filter.html)
>Note that when a condition evaluates to NA the row will be dropped

I found a possible fix by modifying this part in `Majority_classification_extInput.R` 
```
	if (tolower(include_na) == "true"){
		EUKs_ContigID <- contigs_class %>% filter(MajorityKmer_Kaiju_class != "OTHER") %>% select(ContigID) 
		write_delim(EUKs_ContigID, paste0(out_folder, results_filename, ".EUK_NA_contigsIDs_KmerMajority_min",kmer_minLength,"bp_KAIJU_min",refdb_minLength,"bp.txt"), 
```
to
```
	if (tolower(include_na) == "true"){
		EUKs_ContigID <- contigs_class %>% filter(MajorityKmer_Kaiju_class %in% c("EUK", NA)) %>% select(ContigID) # modification DJ
		write_delim(EUKs_ContigID, paste0(out_folder, results_filename, ".EUK_NA_contigsIDs_KmerMajority_min",kmer_minLength,"bp_KAIJU_min",refdb_minLength,"bp.txt"), 
```

New results:
```
cat results/MEGAHIT_assembly/EUKsemble_classification/megahit_sols.contigs.1000.EUK_NA_contigsIDs_KmerMajority_min3000bp_KAIJU_min1000bp.txt             
k141_1419_flag=1_multi=3.0000_len=1442
k141_475_flag=1_multi=3.0000_len=1306
k141_1298_flag=1_multi=1.0000_len=1103
k141_5958_flag=0_multi=1.6596_len=1219
k141_7362_flag=1_multi=2.6556_len=1224

```

Best regards,
Domitille

**Comment by mgabriell1** [comment]
Hi Domitille,
Thanks for pointing this out!
Your solution makes sense, but I think the issue here is something else. 
In theory, kmer-based classification should always be working so it's fine that the `Kaiju_Class` is `NA` but the `Tiara_Class` and `DeepMicrobeFinder_Class` (now `DeepMicroClass_Class`) should have some values.
What is the output from the single tools in their own folder?

Marco

**Comment by mgabriell1** [comment]
Sorry, It makes sense: they are too short and so I guess they are not classified using kmers-based tools, but only reference-based ones. I have implemented your solution :)
I need to finish to test the new version of `CAT_pack` and then I'll push the updated version. 
Thanks again!
